### ISSUE TITLE
[JENKINS-47593] can not to be online without permission

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/ec2-plugin#1548]
<p>After upgrade to 2.86 plugin need extra permission for dynamic script  to make slave online via ssh connection. </p>

<p>I can not use "In-process Script Approval" because this script look like <br/>
'ssh user@​123.212.12.232 ....' and it is dynamic! </p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/pperzyna.svg" title="pperzyna's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=pperzyna">pperzyna</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-47593" target="_blank">can not to be online without permission</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/wfollonier.png" title="wfollonier's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=wfollonier">wfollonier</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Critical
<li><b>component(s)</b>: ec2-plugin
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-12-06T13:46:33+00:00
<li><b>votes</b>: 5
<li><b>watchers</b>: 10
<li><b>imported</b>: 2025-12-06
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrade to 2.86 plugin need extra permission for dynamic script  to make slave online via ssh connection. </p>

<p>I can not use "In-process Script Approval" because this script look like 
'ssh user@123.212.12.232 ....' and it is dynamic! </p></pre>
</details>
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> jglick:</i></summary>

<ul>
<li><i><a class="no-jira-link-rewrite" href="https://issue-redirect.jenkins.io/issue/47593?focusedId=319188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-319188">Comment link</a></i>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-47593?focusedId=319188&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-319188">comment link</a> (no redirect)</i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>To be clear, the “this” that should not be happening is the <tt>NoClassDefFoundError</tt> or whatever it is. The need to manually approve a command-line launch string is an acknowledged issue.</p>
</pre>
</details>

</ul>
</details>

<p>To be clear, the “this” that should not be happening is the <tt>NoClassDefFoundError</tt> or whatever it is. The need to manually approve a command-line launch string is an acknowledged issue.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i><a class="no-jira-link-rewrite" href="https://issue-redirect.jenkins.io/issue/47593?focusedId=322955&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322955">Comment link</a></i>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-47593?focusedId=322955&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-322955">comment link</a> (no redirect)</i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Francis Upton IV
Path:
 pom.xml
 src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java
 src/main/java/hudson/plugins/ec2/SlaveTemplate.java
 src/main/java/hudson/plugins/ec2/UnixData.java
 src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java
 src/main/resources/hudson/plugins/ec2/Messages.properties
<a href="http://jenkins-ci.org/commit/ec2-plugin/180f7d0eae6031d67259a5d86d9d7d382f9eb05b" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/ec2-plugin/180f7d0eae6031d67259a5d86d9d7d382f9eb05b</a>
Log:
  Jenkins 47593 avoid script block (#253)</p>

<ul>
	<li><a href="https://issue-redirect.jenkins.io/issue/47593" title="can not to be online without permission" class="issue-link" data-issue-key="JENKINS-47593"><del>JENKINS-47593</del></a><span class="error">&#91;SECURITY-643&#93;</span> Allow command to be run without approval</li>
</ul>
<ul class="alternate" type="square">
	<li>use the second constructor of CommandLauncher to avoid being blocked by the security fix</li>
</ul>


<ul>
	<li>- adding permission check on unsafe parameter modification</li>
</ul>
<ul class="alternate" type="square">
	<li>adding warning message in case someone is modifying the unsafe parameters</li>
</ul>


<ul>
	<li>- also put the right check on the readResolve</li>
</ul>
<ul class="alternate" type="square">
	<li>regroup the permission error message</li>
</ul>


<ul>
	<li>- change name of the required permission</li>
</ul>


<ul>
	<li><span class="error">&#91;SECURITY-643&#93;</span> Fix exception during start of cloud config</li>
</ul>


<ul>
	<li><span class="error">&#91;maven-release-plugin&#93;</span> prepare release ec2-1.38</li>
</ul>


<ul>
	<li><span class="error">&#91;maven-release-plugin&#93;</span> prepare for next development iteration</li>
</ul>



</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Francis Upton IV<br/>
Path:<br/>
 pom.xml<br/>
 src/main/java/hudson/plugins/ec2/AmazonEC2Cloud.java<br/>
 src/main/java/hudson/plugins/ec2/SlaveTemplate.java<br/>
 src/main/java/hudson/plugins/ec2/UnixData.java<br/>
 src/main/java/hudson/plugins/ec2/ssh/EC2UnixLauncher.java<br/>
 src/main/resources/hudson/plugins/ec2/Messages.properties<br/>
<a href="http://jenkins-ci.org/commit/ec2-plugin/180f7d0eae6031d67259a5d86d9d7d382f9eb05b" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/ec2-plugin/180f7d0eae6031d67259a5d86d9d7d382f9eb05b</a><br/>
Log:<br/>
  Jenkins 47593 avoid script block (#253)</p>

<ul>
	<li><a href="https://issue-redirect.jenkins.io/issue/47593" title="can not to be online without permission" class="issue-link" data-issue-key="JENKINS-47593"><del>JENKINS-47593</del></a><span class="error">&#91;SECURITY-643&#93;</span> Allow command to be run without approval</li>
</ul>
<ul class="alternate" type="square">
	<li>use the second constructor of CommandLauncher to avoid being blocked by the security fix</li>
</ul>


<ul>
	<li>- adding permission check on unsafe parameter modification</li>
</ul>
<ul class="alternate" type="square">
	<li>adding warning message in case someone is modifying the unsafe parameters</li>
</ul>


<ul>
	<li>- also put the right check on the readResolve</li>
</ul>
<ul class="alternate" type="square">
	<li>regroup the permission error message</li>
</ul>


<ul>
	<li>- change name of the required permission</li>
</ul>


<ul>
	<li><span class="error">&#91;SECURITY-643&#93;</span> Fix exception during start of cloud config</li>
</ul>


<ul>
	<li><span class="error">&#91;maven-release-plugin&#93;</span> prepare release ec2-1.38</li>
</ul>


<ul>
	<li><span class="error">&#91;maven-release-plugin&#93;</span> prepare for next development iteration</li>
</ul>
